-- 英语 App 数据模型演示；在独立 psql 连接中执行整个文件。
-- 仅创建临时表，最后回滚。不要作为生产迁移使用。
BEGIN;
SET LOCAL TIME ZONE 'UTC';

CREATE TEMP TABLE app_users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);

CREATE TEMP TABLE app_words (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language_code text NOT NULL,
    lemma text NOT NULL,
    sense_key text NOT NULL,
    definition text NOT NULL,
    UNIQUE (language_code, lemma, sense_key)
);

CREATE TEMP TABLE app_groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES app_users(id),
    title text NOT NULL,
    archived_at timestamptz,
    UNIQUE (id, user_id)
);

CREATE TEMP TABLE app_group_words (
    group_id bigint NOT NULL REFERENCES app_groups(id),
    word_id bigint NOT NULL REFERENCES app_words(id),
    position integer NOT NULL CHECK (position > 0),
    PRIMARY KEY (group_id, word_id),
    UNIQUE (group_id, position)
);

CREATE TEMP TABLE app_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES app_users(id),
    group_id bigint,
    request_key text NOT NULL CHECK (length(request_key) > 0),
    status text NOT NULL CHECK (status IN ('active', 'completed', 'abandoned')),
    started_at timestamptz NOT NULL,
    completed_at timestamptz,
    UNIQUE (user_id, request_key),
    UNIQUE (id, user_id),
    FOREIGN KEY (group_id, user_id) REFERENCES app_groups(id, user_id),
    CHECK (
        (status = 'active' AND completed_at IS NULL)
        OR (status IN ('completed', 'abandoned')
            AND completed_at IS NOT NULL AND completed_at >= started_at)
    )
);

CREATE TEMP TABLE app_session_words (
    session_id bigint NOT NULL REFERENCES app_sessions(id),
    word_id bigint NOT NULL REFERENCES app_words(id),
    word_text_snapshot text NOT NULL,
    PRIMARY KEY (session_id, word_id)
);

CREATE TEMP TABLE app_review_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES app_users(id),
    session_id bigint NOT NULL,
    word_id bigint NOT NULL,
    client_event_id text NOT NULL CHECK (length(client_event_id) > 0),
    is_correct boolean NOT NULL,
    score numeric(5,2) NOT NULL CHECK (score BETWEEN 0 AND 100),
    occurred_at timestamptz NOT NULL,
    UNIQUE (user_id, client_event_id),
    FOREIGN KEY (session_id, user_id) REFERENCES app_sessions(id, user_id),
    FOREIGN KEY (session_id, word_id) REFERENCES app_session_words(session_id, word_id)
);

CREATE TEMP TABLE app_word_progress (
    user_id bigint NOT NULL REFERENCES app_users(id),
    word_id bigint NOT NULL REFERENCES app_words(id),
    mastery smallint NOT NULL CHECK (mastery BETWEEN 0 AND 5),
    due_at timestamptz,
    version integer NOT NULL DEFAULT 0 CHECK (version >= 0),
    algorithm_version text NOT NULL,
    updated_at timestamptz NOT NULL,
    PRIMARY KEY (user_id, word_id)
);

-- 索引对应明确读取；小样本不能据此证明真实产品性能。
CREATE INDEX app_progress_due_idx
    ON app_word_progress (user_id, due_at, word_id) WHERE due_at IS NOT NULL;
CREATE INDEX app_sessions_recent_idx
    ON app_sessions (user_id, started_at DESC, id DESC);
CREATE INDEX app_events_session_word_idx
    ON app_review_events (session_id, word_id);

-- 使用自动生成的 ID；这是全新临时表，下面 ID 从 1 开始。
INSERT INTO app_users (name) VALUES ('Lin'), ('Mei');
INSERT INTO app_words (language_code, lemma, sense_key, definition) VALUES
    ('en', 'bank', 'financial-institution', '银行'),
    ('en', 'bank', 'river-edge', '河岸'),
    ('en', 'practice', 'repeated-training', '练习');
INSERT INTO app_groups (user_id, title) VALUES (1, '我的词组'), (2, 'Mei 的词组');
INSERT INTO app_group_words (group_id, word_id, position) VALUES
    (1, 1, 1), (1, 2, 2), (2, 1, 1);
INSERT INTO app_sessions (user_id, group_id, request_key, status, started_at) VALUES
    (1, 1, 'start-lin-1', 'active', '2026-09-21 09:00:00+00'),
    (2, 2, 'start-mei-1', 'active', '2026-09-21 10:00:00+00');
INSERT INTO app_session_words (session_id, word_id, word_text_snapshot) VALUES
    (1, 1, 'bank：银行'), (1, 2, 'bank：河岸'), (2, 1, 'bank：银行');
INSERT INTO app_review_events
    (user_id, session_id, word_id, client_event_id, is_correct, score, occurred_at)
VALUES (1, 1, 1, 'answer-lin-1', true, 90, '2026-09-21 09:01:00+00');
INSERT INTO app_word_progress
    (user_id, word_id, mastery, due_at, algorithm_version, updated_at)
VALUES
    (1, 1, 2, '2026-09-22 09:00:00+00', 'v1', '2026-09-21 09:01:00+00'),
    (2, 1, 4, NULL, 'v1', '2026-09-21 10:01:00+00');

-- 相同事件键的重试不会新增第二行。
-- 产品还须比对载荷、返回原结果，并仅在首次插入时推进进度。
INSERT INTO app_review_events
    (user_id, session_id, word_id, client_event_id, is_correct, score, occurred_at)
VALUES (1, 1, 1, 'answer-lin-1', true, 90, '2026-09-21 09:01:00+00')
ON CONFLICT (user_id, client_event_id) DO NOTHING;

-- 每个内部块只捕获期望的错误；错误没发生或类型不符都会令脚本失败。
-- 这些是模型检查，不要求记忆 DO / EXCEPTION 语法。
DO $$
BEGIN
    IF (SELECT count(*) FROM app_review_events) <> 1 THEN
        RAISE EXCEPTION '同一事件重试产生了重复行';
    END IF;

    BEGIN
        INSERT INTO app_review_events
            (user_id, session_id, word_id, client_event_id, is_correct, score, occurred_at)
        VALUES (1, 1, 1, 'answer-lin-1', true, 90, '2026-09-21 09:01:00+00');
        RAISE EXCEPTION '重复事件没有被拒绝';
    EXCEPTION WHEN unique_violation THEN NULL;
    END;

    BEGIN
        INSERT INTO app_sessions (user_id, group_id, request_key, status, started_at)
        VALUES (1, 2, 'bad-group', 'active', '2026-09-21 09:00:00+00');
        RAISE EXCEPTION '跨用户使用私人组没有被拒绝';
    EXCEPTION WHEN foreign_key_violation THEN NULL;
    END;

    BEGIN
        INSERT INTO app_review_events
            (user_id, session_id, word_id, client_event_id, is_correct, score, occurred_at)
        VALUES (2, 1, 1, 'bad-owner', true, 90, '2026-09-21 09:01:00+00');
        RAISE EXCEPTION '跨用户提交会话事件没有被拒绝';
    EXCEPTION WHEN foreign_key_violation THEN NULL;
    END;

    BEGIN
        INSERT INTO app_review_events
            (user_id, session_id, word_id, client_event_id, is_correct, score, occurred_at)
        VALUES (1, 1, 3, 'bad-target', true, 90, '2026-09-21 09:01:00+00');
        RAISE EXCEPTION '非目标词没有被拒绝';
    EXCEPTION WHEN foreign_key_violation THEN NULL;
    END;

    BEGIN
        INSERT INTO app_review_events
            (user_id, session_id, word_id, client_event_id, is_correct, score, occurred_at)
        VALUES (1, 1, 1, 'bad-score', true, 101, '2026-09-21 09:01:00+00');
        RAISE EXCEPTION '越界分数没有被拒绝';
    EXCEPTION WHEN check_violation THEN NULL;
    END;

    BEGIN
        INSERT INTO app_review_events
            (user_id, session_id, word_id, client_event_id, is_correct, score, occurred_at)
        VALUES (1, 1, 1, 'null-score', true, NULL, '2026-09-21 09:01:00+00');
        RAISE EXCEPTION '空分数没有被拒绝';
    EXCEPTION WHEN not_null_violation THEN NULL;
    END;

    BEGIN
        INSERT INTO app_sessions
            (user_id, group_id, request_key, status, started_at, completed_at)
        VALUES (1, 1, 'bad-state', 'active', '2026-09-21 09:00:00+00', '2026-09-21 09:01:00+00');
        RAISE EXCEPTION '活动会话带结束时间没有被拒绝';
    EXCEPTION WHEN check_violation THEN NULL;
    END;

    BEGIN
        INSERT INTO app_sessions
            (user_id, group_id, request_key, status, started_at, completed_at)
        VALUES (1, 1, 'bad-time', 'completed', '2026-09-21 09:00:00+00', '2026-09-20 09:00:00+00');
        RAISE EXCEPTION '结束早于开始没有被拒绝';
    EXCEPTION WHEN check_violation THEN NULL;
    END;

    BEGIN
        INSERT INTO app_word_progress
            (user_id, word_id, mastery, algorithm_version, updated_at)
        VALUES (1, 1, 1, 'v1', '2026-09-21 09:01:00+00');
        RAISE EXCEPTION '重复进度没有被拒绝';
    EXCEPTION WHEN unique_violation THEN NULL;
    END;

    IF (SELECT count(*) FROM app_sessions) <> 2
        OR (SELECT count(*) FROM app_review_events) <> 1
        OR (SELECT count(*) FROM app_word_progress) <> 2 THEN
        RAISE EXCEPTION '失败写入遗留了额外记录';
    END IF;
END;
$$;

SELECT 'model checks passed' AS check_result;

-- 固定截止时刻使结果可复现，应该仅返回 Lin 的 bank（银行）。
SELECT p.user_id, w.lemma, w.definition, p.mastery, p.due_at
FROM app_word_progress p
JOIN app_words w ON w.id = p.word_id
WHERE p.user_id = 1 AND p.due_at <= TIMESTAMPTZ '2026-09-23 00:00:00+00'
ORDER BY p.due_at, p.word_id
LIMIT 20;

ROLLBACK;
